### ISSUE TITLE
mrview: Segfault / context errors

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1093]
- When running in debug mode, I get a context error on close, from the destructor of `std::unordered_map<size_t, GL::Texture> Image::tex_4d_cache`. I tried wrapping it thus:
```
Image::~Image()
{
  MRView::GrabContext context;
  ASSERT_GL_MRVIEW_CONTEXT_IS_CURRENT;
  std::unordered_map<size_t, GL::Texture>().swap(tex_4d_cache);
}
```
, but the context assertion still fails when the `GL::Texture`'s are destroyed. Appears to occur if a 4D image is opened in the overlay tool, or if lightbox mode is activated with a 4D main image.

- `mrview image1.mif -overlay.load image2.mif` segfaults, deep within Qt (5.9.1; no meaningful backtrace to *MRtrix3* code). Crashes regardless of whether `image2.mif` is 3D or 4D, so not sure whether or not it's at all related to the first point; but I discovered them at the same time, so maybe?

**Comment by jdtournier** [comment]
- OK, I think the issue here is that the order of execution for destruction in C++ is destructor code first, then destructor for member variables (then base class destructor, etc). So if the main application's destructor destroys the OpenGL context, and then its members, and those members contain textures, then they simply can't be released without error. Good thing is though that they shouldn't _need_ to be released since the entire context has been freed... Maybe we can find a way to detect when the context doesn't exist and just not try to delete the Texture in this case...?

- no idea about the second one, but I'm pretty sure I've used just such a command not long ago, and it worked fine then... I'll check when I'm back at my desk next week.

**Comment by Lestropie** [comment]
Unlike #378, on my work desktop I get a segfault rather than a warning when using `-overlay.load`, as originally reported above; #1586 does *not* resolve this issue.

Backtrace (built using Qt 5.12.1 with debugging symbols):

```text
[rob@bri-pub-122 sub-01]$ gdb --args mrview anat/sub-01_tissues3D.nii.gz -overlay.load anat/sub-01_T1w.nii.gz 
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mrview...done.
(gdb) r
Starting program: /home/rob/src/mrtrix3/bin/mrview anat/sub-01_tissues3D.nii.gz -overlay.load anat/sub-01_T1w.nii.gz
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffedfc7700 (LWP 27660)]
[New Thread 0x7fffe7d61700 (LWP 27661)]
[New Thread 0x7fffe7560700 (LWP 27662)]
[New Thread 0x7fffe63df700 (LWP 27663)]

Thread 1 "mrview" received signal SIGSEGV, Segmentation fault.
0x00007ffff5e32e67 in QVariantAnimationPrivate::valueAt (this=0x6e007375, step=0)
    at ../../include/QtCore/../../src/corelib/tools/qpair.h:148
148	../../include/QtCore/../../src/corelib/tools/qpair.h: No such file or directory.
(gdb) bt
#0  0x00007ffff5e32e67 in QVariantAnimationPrivate::valueAt(double) const (this=0x6e007375, step=0)
    at ../../include/QtCore/../../src/corelib/tools/qpair.h:148
#1  0x00007ffff5e33961 in QVariantAnimation::keyValueAt(double) const
    (this=this@entry=0x5555562eda30, step=step@entry=0) at animation/qvariantanimation.h:110
#2  0x00007ffff5e339a2 in QVariantAnimation::startValue() const (this=this@entry=0x5555562eda30)
    at animation/qvariantanimation.cpp:526
#3  0x00007ffff5e370d1 in QPropertyAnimation::updateState(QAbstractAnimation::State, QAbstractAnimation::State) (this=0x5555562eda30, newState=<optimized out>, oldState=QAbstractAnimation::Stopped)
    at animation/qpropertyanimation.cpp:280
#4  0x00007ffff5e3104c in QAbstractAnimationPrivate::setState(QAbstractAnimation::State)
    (newState=QAbstractAnimation::Running, this=0x55555632b180)
    at ../../include/QtCore/../../src/corelib/tools/qsharedpointer_impl.h:167
#5  0x00007ffff5e3104c in QAbstractAnimation::start(QAbstractAnimation::DeletionPolicy)
    (this=<optimized out>, policy=<optimized out>) at animation/qabstractanimation.cpp:1357
#6  0x00007ffff6ac6cd7 in QWidgetAnimator::animate(QWidget*, QRect const&, bool)
    (this=this@entry=0x555555feb070, widget=<optimized out>, _final_geometry=..., animate=<optimized out>, animate@entry=false) at widgets/qwidgetanimator.cpp:109
#7  0x00007ffff6b00241 in QDockAreaLayout::apply(bool)
    (this=this@entry=0x555555feac10, animate=animate@entry=false) at widgets/qdockarealayout.cpp:3224
#8  0x00007ffff6b30789 in QMainWindowLayoutState::apply(bool)
    (animated=<optimized out>, this=0x555555feab38) at widgets/qmainwindowlayout.cpp:670
#9  0x00007ffff6b30789 in QMainWindowLayout::applyState(QMainWindowLayoutState&, bool)
    (this=this@entry=0x555555feaad0, newState=..., animate=animate@entry=false)
    at widgets/qmainwindowlayout.cpp:2709
#10 0x00007ffff6b340f2 in QMainWindowLayout::setGeometry(QRect const&) (this=0x555555feaad0, _r=...)
    at widgets/qmainwindowlayout.cpp:1956
#11 0x00007ffff69f7778 in QLayoutPrivate::doResize(QSize const&) (this=this@entry=0x555555f5db50, r=...)
    at ../../include/QtCore/../../src/corelib/tools/qrect.h:184
#12 0x00007ffff69f8866 in QLayout::activate() (this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qsize.h:119
#13 0x00007ffff69f8a6c in QLayout::widgetEvent(QEvent*) (this=<optimized out>, e=e@entry=0x5555562a93a0)
    at kernel/qlayout.cpp:618
#14 0x00007ffff69d9e08 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=
    0x555555e7d650, receiver=receiver@entry=0x7fffffffd150, e=e@entry=0x5555562a93a0)
    at kernel/qapplication.cpp:3723
#15 0x00007ffff69e15f1 in QApplication::notify(QObject*, QEvent*)
    (this=0x555555e86de0, receiver=0x7fffffffd150, e=0x5555562a93a0) at kernel/qapplication.cpp:3483
#16 0x00007ffff6006df9 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    (receiver=0x7fffffffd150, event=0x5555562a93a0)
    at ../../include/QtCore/5.12.2/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:322
#17 0x00007ffff6009ee8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
    (receiver=0x0, event_type=0, data=0x555555e80360) at kernel/qcoreapplication.cpp:1799
#18 0x00007ffff605d6c4 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x555556031d80)
    at kernel/qeventdispatcher_glib.cpp:276
#19 0x00007ffff2abd7bf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff2abf739 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff2abf77e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff605cc99 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    (this=0x55555601f910, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#23 0x00007ffff6005a8c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)
    (this=this@entry=0x7fffffffd070, flags=..., flags@entry=...)
    at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#24 0x00007ffff600dde6 in QCoreApplication::exec() ()
    at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#25 0x0000555555a7c69e in run() () at cmd/mrview.cpp:100
#26 0x0000555555a7c22c in main(int, char**) (cmdline_argc=4, cmdline_argv=0x7fffffffe208)
    at ./core/command.h:98
```
