### ISSUE TITLE
dwiintensitynorm: command failed

### ISSUE THREAD

**Issue by chunhungyeh** [MRtrix3/mrtrix3#649]
Hi all,

Playing around with the `dwiintensitynorm` script but got an error.

Version:
```
== mrview 0.3.14-629-gfb9db785 ==
64 bit release version, built Jun  2 2016, using Eigen 3.2.8
```

Things were going well until:
```
Command: mrmath input_transformed/* mean initial_template.mif
mrmath: [ERROR] mrmath requires either multiple input images, or the -axis option to be provided
population_template: [ERROR] Command failed: mrmath input_transformed/* mean initial_template.mif
population_template: Changing back to original directory (/private/tmp/dwiintensitynorm-tmp-N7OP3R)
population_template: Contents of temporary directory kept, location: /private/tmp/dwiintensitynorm-tmp-N7OP3R/population_template
dwiintensitynorm: [ERROR] Command failed: population_template fa -mask_dir /tmp/dwiintensitynorm-tmp-N7OP3R/mask fa_template.mif -linear_scale 0.25,0.5,1.0,1.0 -nl_scale 0.5,0.75,1.0,1.0,1.0 -nl_niter 5,5,5,5,5 -warp_dir warps -nocleanup -tempdir population_template
dwiintensitynorm: Changing back to original directory (/Users/chyeh/test_data)
dwiintensitynorm: Deleting temporary directory /tmp/dwiintensitynorm-tmp-N7OP3R/
```

**Comment by Lestropie** [comment]
OK I must have missed that one during #629. Because the `runCommand()` function now uses `subprocess` rather than `os.system()`, the command string isn't going through a shell interpreter, and therefore wildcards can't be used. Gimme a minute.

**Comment by Lestropie** [comment]
@chunhungyeh Can you please have a go at it on the `population_template_wildcard_fix` branch, since you've got data ready to go?

**Comment by chunhungyeh** [comment]
@Lestropie Just tried it and got these errors:
```
Command: mrconvert nl_template4.mif /private/tmp/dwiintensitynorm-tmp-POBONS/fa_template.mif
Traceback (most recent call last):
  File "/Users/chyeh/Toolkit/mrtrix3/scripts/population_template", line 363, in <module>
    shutil.copy('warps/', getUserPath(lib.app.args.warp_dir, False))
NameError: name 'shutil' is not defined
dwiintensitynorm: [ERROR] Command failed: population_template fa -mask_dir /tmp/dwiintensitynorm-tmp-POBONS/mask fa_template.mif -linear_scale 0.25,0.5,1.0,1.0 -nl_scale 0.5,0.75,1.0,1.0,1.0 -nl_niter 5,5,5,5,5 -warp_dir warps -nocleanup -tempdir population_template
dwiintensitynorm: Changing back to original directory (/Users/chyeh/test_data)
dwiintensitynorm: Deleting temporary directory /tmp/dwiintensitynorm-tmp-POBONS/
```

**Comment by Lestropie** [comment]
Ack. Try again?

**Comment by chunhungyeh** [comment]
```
Traceback (most recent call last):
  File "/Users/chyeh/Toolkit/mrtrix3/scripts/population_template", line 363, in <module>
    shutil.copy('warps/', getUserPath(lib.app.args.warp_dir, False))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: 'warps/'
dwiintensitynorm: [ERROR] Command failed: population_template fa -mask_dir /tmp/dwiintensitynorm-tmp-YUPED6/mask fa_template.mif -linear_scale 0.25,0.5,1.0,1.0 -nl_scale 0.5,0.75,1.0,1.0,1.0 -nl_niter 5,5,5,5,5 -warp_dir warps -nocleanup -tempdir population_template
```

**Comment by Lestropie** [comment]
OK, so `population_template` nearly finished, it just bugged out writing the outputs because I used the wrong function. _Hopefully_ this last one will get it...

**Comment by chunhungyeh** [comment]
All good now. :)
