### ISSUE TITLE
mrconvert axes insertion assert failure

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#977]
mrconvert's -axes addition using -1 as permutation index fails:

`mrconvert image3d.mif -axes 0,1,2,-1 image4d.mif`

It bails out in the [threaded_copy](https://github.com/MRtrix3/mrtrix3/blob/master/cmd/mrconvert.cpp#L231) with

```mrconvert: ./core/image_helpers.h:435: MR::Helper::Index<MR::Image<double> >::Index(ImageType &, size_t) [ImageType = MR::Image<double>]: Assertion `axis < image.ndim()' failed.
Aborted```

**Comment by maxpietsch** [comment]
It seems to be a signed overflow of `axis (= 18446744073709551615)` in the constructor of `Helper::Index`. 

Backtrace:
```
(gdb) bt
#0  0x00007ffff68a8c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff68ac028 in __GI_abort () at abort.c:89
#2  0x00007ffff68a1bf6 in __assert_fail_base (fmt=0x7ffff69f5bf8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x504d4b "axis < image.ndim()", file=file@entry=0x5046cf "./core/image_helpers.h", line=line@entry=436, 
    function=function@entry=0x507a30 "MR::Helper::Index<MR::Image<double> >::Index(ImageType &, size_t) [ImageType = MR::Image<double>]")
    at assert.c:92
#3  0x00007ffff68a1ca2 in __GI___assert_fail (assertion=0x504d4b "axis < image.ndim()", file=0x5046cf "./core/image_helpers.h", line=436, 
    function=0x507a30 "MR::Helper::Index<MR::Image<double> >::Index(ImageType &, size_t) [ImageType = MR::Image<double>]") at assert.c:101
#4  0x00000000004d4268 in MR::Helper::Index<MR::Image<double> >::Index(MR::Image<double>&, unsigned long) ()
#5  0x00000000004d3fa4 in MR::Helper::Index<MR::Adapter::PermuteAxes<MR::Image<double> > >::operator+=(long) ()
#6  0x0000000000460027 in MR::(anonymous namespace)::ThreadedLoopRunInner<2, MR::(anonymous namespace)::__copy_func, MR::Adapter::PermuteAxes<MR::Image<double> >, MR::Image<double> >::operator()(MR::Iterator const&) ()
#7  0x00000000004d1045 in void MR::threaded_copy_with_progress_message<MR::Adapter::PermuteAxes<MR::Image<double> >, MR::Image<double> >(std::string const&, MR::Adapter::PermuteAxes<MR::Image<double> >&, MR::Image<double>&, unsigned long, unsigned long, unsigned long) ()
#8  0x00000000004cd1c8 in void MR::threaded_copy_with_progress<MR::Adapter::PermuteAxes<MR::Image<double> >, MR::Image<double> >(MR::Adapter::PermuteAxes<MR::Image<double> >&, MR::Image<double>&, unsigned long, unsigned long, unsigned long) ()
#9  0x000000000047285b in void copy_permute<double>(MR::Header&, MR::Header&, MR::vector<MR::vector<int, 0>, 0> const&, std::string const&) ()
#10 0x0000000000418dcd in run() ()
#11 0x0000000000413fd8 in main ()
```
